Repository SIAnalytics/siatune, pull requests merged in 2022-12, with the labels that each got.

#80 [Fix] Continuous function numerical error
  siatune/mm/tasks/cont_test_func.py
Labels: bug

#87 [Support] comparison between normal objects and objects in container
  siatune/utils/container.py
Labels: bug

#88 [Fix] CI workflow not to run when pr is draft
  .github/workflows/build_unit_test.yaml
  .github/workflows/build_unit_test_pass.yaml
Labels: ci

#79 [Fix] Fix choice space to handle case where no alias is set
  siatune/ray/spaces/choice.py
Labels: bug

#89 [Fix] Fix CI check for Draft PR
  .github/workflows/build_unit_test.yaml
  .github/workflows/build_unit_test_pass.yaml
Labels: bug, ci

#95 [Add] pr templates
  .github/pull_request_template.md
Labels: documentation

#81 [Refactor] Upgrade ray from 1.9.1 to 2.1.0
  configs/_base_/scheduler/asynchb.py
  configs/mmcls/mmcls_cifar_100_asynchb_nevergrad_pso.py
  configs/mmdet/mmdet_asynchb_nevergrad_pso.py
  configs/mmseg/mmseg_asynchb_nevergrad_pso.py
  requirements/optional.txt
  requirements/runtime.txt
  setup.cfg
  siatune/apis/analysis.py
  siatune/apis/tune.py
  siatune/mm/context/rewriters/dump.py
  siatune/mm/context/rewriters/path.py
  siatune/mm/hooks/checkpoint.py
  siatune/mm/hooks/reporter.py
  siatune/mm/tasks/base.py
  siatune/mm/tasks/mmcls.py
  siatune/mm/tasks/mmdet.py
  siatune/mm/tasks/mmseg.py
  siatune/mm/tasks/mmtrainbase.py
  siatune/ray/__init__.py
  siatune/ray/callbacks/mlflow.py
  siatune/ray/config.py
  siatune/ray/schedulers/pbt.py
  siatune/ray/searchers/builder.py
  siatune/ray/searchers/flaml.py
  siatune/ray/searchers/hyperopt.py
  siatune/ray/searchers/nevergrad.py
  siatune/ray/spaces/base.py
  siatune/ray/spaces/choice.py
  siatune/ray/spaces/sample_from.py
  siatune/ray/tuner.py
  siatune/run.py
  tests/test_apis/test_apis.py
  tests/test_mm/test_rewriters.py
  tests/test_mm/test_tasks.py
  tests/test_mm/test_tasks/test_base.py
  tests/test_mm/test_tasks/test_blackbox.py
  tests/test_mm/test_tasks/test_mmtask.py
Labels: BC Break
